# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-cs_nrGiTjlCJu_FyMmCJEBZTfWC7UE
"""

import streamlit as st #Import the library after installation

col1, col2 = st.columns(2)

with col1:

option = st.selectbox(
    "Catégories",
    ("Email", "Home phone", "Mobile phone"),
    index=None,
    placeholder="Selectionner la catégorie du livre...",
)

with col2:
    option = st.selectbox(
    "TEST TEST",
    ("Email", "Home phone", "Mobile phone"),
)

st.write("You selected:", option)
