# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-cs_nrGiTjlCJu_FyMmCJEBZTfWC7UE
"""

import streamlit as st #Import the library after installation

option = st.selectbox(
    "How would you like to be contacted?",
    ("Email", "Home phone", "Mobile phone"),
    index=None,
    placeholder="Selectionner la catégorie du livre...",
)
